name: Build, Push Docker Image to Docker Hub and Deploy to Azure

on:
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: read

jobs:
  build-push-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Azure login
      uses: azure/login@v2
      with:
        client-id: ${{ secrets.AZURE_CLIENT_ID }}
        tenant-id: ${{ secrets.AZURE_TENANT_ID }}
        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

    - name: Deploy to Azure Container Instance
      run: |
        az container create \
          --resource-group MyResourceGroup \
          --name mycontainerinstance2 \
          --image ${{ secrets.DOCKER_USERNAME }}/opc:latest \
          --cpu 2 \
          --memory 4 \
          --port 5005 \
          --dns-name-label mycontainerdns4 \
          --environment-variables WEBSITES_PORT=5005

    - name: Get logs from Azure Container Instance
      run: |
        az container logs --resource-group MyResourceGroup --name mycontainerinstance
